on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            APP_DIR=/var/www/travifai-app
            cd $APP_DIR
            if [ ! -d .git ]; then
              rm -rf * 
              git clone https://github.com/${{ github.repository }} .
            else
              git fetch origin
            fi
            git checkout main
            git pull --ff-only origin main
            npm install --omit=dev
            pm2 startOrReload ecosystem.config.js || pm2 start server.js --name travifai-task-api
            pm2 save
            #
